<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue'
import type { AgentResponseV1, AlertViewV1, CareTaskV1, DashboardV1 } from '@carehub/shared-contracts'
import AppIcon from '@/components/AppIcon.vue'
import CareAgentSheet from '@/components/CareAgentSheet.vue'
import { coreAdapter, currentSubjectId } from '@/services/adapter'
import { useUiStore } from '@/stores/ui'
const dashboard = ref<DashboardV1 | null>(null); const today = ref<AgentResponseV1 | null>(null); const alerts = ref<AlertViewV1[]>([]); const tasks = ref<CareTaskV1[]>([]); const loading = ref(true); const error = ref(''); const ui = useUiStore(); let retryTimer: ReturnType<typeof setTimeout> | undefined; let reconcileTimer: ReturnType<typeof setTimeout> | undefined; let reconcileInterval: ReturnType<typeof setInterval> | undefined
const careAgentOpen = ref(false)
const alertLabel = (kind: string) => kind === 'FALL_RISK' ? '有 1 条安全记录需要留意' : '有 1 条安全记录需要留意'
const formatTime = (value: string) => new Intl.DateTimeFormat('zh-CN',{hour:'2-digit',minute:'2-digit',hour12:false}).format(new Date(value))
const important = computed(() => [...alerts.value.filter(x=>x.status==='OPEN').map(x=>alertLabel(x.kind)), ...tasks.value.filter(x=>x.evidence_state==='UNKNOWN').map(x=>'服药状态待确认')])
async function load() { loading.value=true; error.value=''; try { const [d,a,t,ai] = await Promise.all([coreAdapter.getDashboard(currentSubjectId),coreAdapter.getAlerts(currentSubjectId),coreAdapter.getTasks(currentSubjectId),coreAdapter.getAgent(currentSubjectId,'TODAY_STATUS')]); dashboard.value=d; alerts.value=a; tasks.value=t; today.value=ai; ui.markTrusted(d.last_updated_at); ui.setNetwork(false); if (retryTimer) clearTimeout(retryTimer); retryTimer=undefined } catch(e) { error.value=(e as Error).message; ui.setNetwork(true); if (!retryTimer) retryTimer=setTimeout(()=>{retryTimer=undefined;void load()},1000) } finally { loading.value=false; if (!reconcileTimer) reconcileTimer=setTimeout(()=>{reconcileTimer=undefined;void load()},1000) } }
const online=()=>load(); const offline=()=>ui.setNetwork(true); onMounted(()=>{void load();reconcileInterval=setInterval(()=>void load(),1000);addEventListener('online',online);addEventListener('offline',offline)});onUnmounted(()=>{removeEventListener('online',online);removeEventListener('offline',offline);if(retryTimer)clearTimeout(retryTimer);if(reconcileTimer)clearTimeout(reconcileTimer);if(reconcileInterval)clearInterval(reconcileInterval)})
</script>
<template><main class="app-shell home-page"><header class="top-bar"><div><p class="overline">我的家庭 · {{ dashboard?.family_member.display_name || '—' }}</p><h1>概览</h1></div><button class="avatar-button" type="button" aria-label="当前家庭成员">家</button></header>
<div v-if="ui.isOffline" class="offline-banner">当前内容可能不是实时 · 最后可信快照：{{ ui.lastTrustedAt || '暂无' }}</div>
<section v-if="loading" class="skeleton-card" aria-busy="true"><i/><i/><i/></section><section v-else-if="error" class="empty-state warning"><h2>暂时无法加载</h2><p>{{ error }}</p><button class="text-action" @click="load">重试</button></section>
<template v-else-if="dashboard"><section class="ai-hero"><p>CareHub 智能照护</p><h2>今天整体平稳<template v-if="today?.unknowns?.length">，有 {{ today.unknowns.length }} 项状态待确认</template></h2><p class="ai-hero__description">已分析今天的提醒、安全和关怀记录</p><div><span>{{ important.length }} 项值得关注</span><span>{{ today?.unknowns?.length || 0 }} 项待确认</span></div><small>数据更新至 {{ formatTime(dashboard.last_updated_at) }}</small><div class="ai-hero__actions"><RouterLink to="/reports">查看今日简报 <AppIcon name="chevron"/></RouterLink><button type="button" @click="careAgentOpen=true"><AppIcon name="sparkles" :size="16"/>问 CareAgent</button></div></section>
<div class="section-heading"><h2>AI 今日关注</h2><RouterLink to="/reports">查看全部</RouterLink></div><section class="ios-list"><div v-if="!important.length" class="list-row"><span class="row-icon green"><AppIcon name="check"/></span><span class="row-main"><b>暂无需优先处理的事项</b><small>当前已授权记录中没有新的关注项</small></span></div><RouterLink v-for="(item,index) in important" :key="item" :to="item.includes('服药')?'/tasks':'/reports'" class="list-row"><span class="row-icon" :class="index===0?'amber':'red'"><AppIcon :name="item.includes('服药')?'pill':'shield'"/></span><span class="row-main"><b>{{ item }}</b><small>{{ item.includes('服药') ? '系统只有提醒记录，完成情况仍待确认' : '查看今天的安全记录' }}</small></span><AppIcon name="chevron" class="chevron"/></RouterLink></section>
<div class="metric-grid"><RouterLink to="/tasks" class="metric-card"><span class="metric-icon blue"><AppIcon name="clock"/></span><b>{{ tasks.length }}</b><small>今日提醒</small></RouterLink><RouterLink to="/reports" class="metric-card"><span class="metric-icon green"><AppIcon name="chart"/></span><b>{{ alerts.length }}</b><small>安全记录</small></RouterLink></div>
<div class="section-heading"><h2>今天</h2><RouterLink to="/tasks">查看全部</RouterLink></div><section class="ios-list"><RouterLink to="/tasks" class="list-row"><span class="row-icon amber"><AppIcon name="pill"/></span><span class="row-main"><b>提醒与任务</b><small>{{ tasks.length ? `今天 ${formatTime(tasks[0].scheduled_at)}` : '暂无任务' }}</small></span><AppIcon name="chevron" class="chevron"/></RouterLink><RouterLink to="/care" class="list-row"><span class="row-icon purple"><AppIcon name="heart"/></span><span class="row-main"><b>关怀问候</b><small>向家人表达关心或建议确认状态</small></span><AppIcon name="chevron" class="chevron"/></RouterLink></section></template></main><CareAgentSheet v-model:open="careAgentOpen" /></template>
